### ISSUE TITLE
script is not located in bin/ directory and more

### ISSUE THREAD

**Issue by XSven** [briandfoy/scriptdist#11]
1. The script that is passed to the `scriptdist` utility is not stored in the _bin/_ directory  (already mentioned in #10).
2. If I am using foo.pl as my script name, configuring the project (`perl Makefile.PL`) raises the "Warning: NAME must be a package name". Maybe you have an idea how to normalize a common perl script name (starting with a lowercase letter and having the` .pl` filename extension) to a draft module name that doesn't raise this warning.
3. _MYMETA.json_ and _MYMETA.yml_ are missing in the _.gitignore_.

**Comment by briandfoy** [comment]
I'm not going to spend a lot of time adjusting scriptdist, but if there are things you really want, you can make adjustments and submit patches.

It's also easier to have one topic per issue. For very trivial things, such as adding a new pattern to .gitignore, patches are even better. You get the immediate effect locally, it takes less time for me to deal with it. And, in the repo you'd get credit for the change.

1. There's not a requirement to store scripts in *bin/*, but if this is something that you like you can submit a patch. Is there something that's causing a problem with its location?

2. The script name is the script name. This little utility is designed to get you started and let you make decisions and adjustments later. I don't have an idea on how to satisfy this warning, and I just ignore it (or adjust things manually).

3. I updated the .gitignore template.

**Comment by XSven** [comment]
noted with thanks
