### ISSUE TITLE
Bad links to App::scriptdist

### ISSUE THREAD

**Issue by msestak** [briandfoy/scriptdist#2]
App::scriptdist is not available on search.cpan.org and metacpan.org. Links in documentation lead nowhere. scriptdist is available on http://search.cpan.org/~bdfoy/scriptdist-0.23/ and can be installed with:

```
cpanm http://search.cpan.org/CPAN/authors/id/B/BD/BDFOY/scriptdist-0.23.tar.gz
```

and probably cloning from github but I didn't try that.

**Comment by briandfoy** [comment]
Is there something you saw that mentioned App::scriptdist? I don't think I've ever uploaded it to CPAN. The docs for the released version only point to the GitHub repository.
