### ISSUE TITLE
scriptdist? Really?

### ISSUE THREAD

**Issue by sciurius** [briandfoy/scriptdist#3]
For a couple of seconds I had hoped that this tool would provide *a*, if not *the*, correct way to set up a script-only (Meta)CPAN distribution. Unfortunately it feels stillborn... 

From the very start of CPAN there has been a need to distribute script-only kits. Many attempts were made, AFAIK all failed. CPAN accepted ordinary kits with only scripts but MetaCPAN seems to be more restrictive.

If scriptdist is not functional, what is?

**Comment by briandfoy** [comment]
This wraps a CPAN-distribution around a program so you can install it with CPAN. It does what I intended. So far it does what I want it to. You might be thinking of the Script Archive part of CPAN, but that was manually managed and almost never used. The cpan clients weren't able to install those.

I don't have a recommendation for any other tool.
